Standard sub READMEs
companieshouse/styleguides pull request #67
Opened 2023-04-04 09:53 UTC by ljgeorge

Add standard sub-README files as suggested by @sbasile-ch to make it easier to find

2023-04-04 11:10 UTC, sbasile-ch approved these changes
Thanks for this, @ljgeorge 
My only comment is [this PR](https://github.com/companieshouse/styleguides/pull/68)

2023-04-11 10:23 UTC, sroberts2 requested changes

2023-04-11 10:23 UTC, sroberts2 commented on READMEs.md
> +To help with support in service repos there should be subordinate READMEs linked to the main README as follows
This reads as compulsory and some Repo's will not need these, should we rewrite it to use the words `where applicable` somewhere?

2023-05-15 10:39 UTC, sroberts2 approved these changes

2023-05-15 10:41 UTC, merged